nelmio_api_doc:
    documentation:
        info:
            title: Symfony Task Manager API
            description: Web API that can create tasks for users to us as to-do's
            version: 0.2.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
